#!/usr/bin/env bash

if [[ -z "${REZ_SCRIPTS_ROOT+xxx}" ]]; then
 REZ_SCRIPTS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
 source ${REZ_SCRIPTS_ROOT}/_configure-rez-scripts.sh ${REZ_SCRIPTS_ROOT};
fi

export REZ_RELEASE_TYPE=stable

${REZ_LOCATION}/rez-stable "$@"
